baseURL = 'https://www.samanthony.xyz/'
languageCode = 'en-us'
title = "Sam Anthony's Webpage"
theme = 'aoidh'

[params]
  [params.author]
    name = "Sam Anthony"
    email = "sam@samanthony.xyz"

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
