baseURL = 'https://www.samanthony.xyz/'
languageCode = 'en-us'
title = 'Sam Anthony'
theme = 'aoidh'
enableGitInfo = true

[params]
  [params.author]
    name = 'Sam Anthony'
    email = 'sam@samanthony.xyz'
  [params.repo]
    url = 'https://git.samanthony.xyz/samanthony.xyz/'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1

  [[menus.main]]
    name = 'Résumé'
    pageRef = 'resume'
    weight = 2

  [[menus.main]]
    name = 'Articles'
    pageRef = '/articles'
    weight = 3

  [[menus.main]]
    name = 'Projects'
    pageRef = '/projects'
    weight = 4

[module]
  [[module.mounts]]
    source = 'modules/fonts/plex/packages/plex-serif/fonts/split/woff2'
    target = 'static/fonts/plex/packages/plex-serif/fonts/split/woff2'

  # Default mounts
  [[module.mounts]]
    disableWatch = false
    source = 'content'
    target = 'content'
    [module.mounts.sites]
      [module.mounts.sites.complements]
      [module.mounts.sites.matrix]
  [[module.mounts]]
    disableWatch = false
    source = 'data'
    target = 'data'
    [module.mounts.sites]
      [module.mounts.sites.complements]
      [module.mounts.sites.matrix]
  [[module.mounts]]
    disableWatch = false
    source = 'layouts'
    target = 'layouts'
    [module.mounts.sites]
      [module.mounts.sites.complements]
      [module.mounts.sites.matrix]
  [[module.mounts]]
    disableWatch = false
    source = 'i18n'
    target = 'i18n'
    [module.mounts.sites]
      [module.mounts.sites.complements]
      [module.mounts.sites.matrix]
  [[module.mounts]]
    disableWatch = false
    source = 'archetypes'
    target = 'archetypes'
    [module.mounts.sites]
      [module.mounts.sites.complements]
      [module.mounts.sites.matrix]
  [[module.mounts]]
    disableWatch = false
    source = 'assets'
    target = 'assets'
    [module.mounts.sites]
      [module.mounts.sites.complements]
      [module.mounts.sites.matrix]
  [[module.mounts]]
    disableWatch = false
    source = 'static'
    target = 'static'
    [module.mounts.sites]
      [module.mounts.sites.complements]
      [module.mounts.sites.matrix]
