baseURL = 'https://www.samanthony.xyz/'
languageCode = 'en-us'
title = "Sam Anthony"
theme = 'aoidh'

[params]
  [params.author]
    name = "Sam Anthony"
    email = "sam@samanthony.xyz"

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 2

  [[menus.main]]
    name = 'Projects'
    url = 'http://git.samanthony.xyz/'
    weight = 3

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 4

  [[menus.main]]
    name = 'Foo'
    pageRef = '/foo'
    weight = 4

  [[menus.main]]
    name = 'Bar'
    pageRef = '/bar'
    weight = 4

  [[menus.main]]
    name = 'Baz'
    pageRef = '/baz'
    weight = 4
