baseURL = 'https://www.samanthony.xyz/'
languageCode = 'en-us'
title = "Sam Anthony"
theme = 'aoidh'

[params]
  [params.author]
    name = "Sam Anthony"
    email = "sam@samanthony.xyz"

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1

  [[menus.main]]
    name = 'Auto'
    pageRef = '/auto'
    weight = 2

  [[menus.main]]
    name = 'Articles'
    pageRef = '/articles'
    weight = 3

  [[menus.main]]
    name = 'Projects'
    pageRef = '/projects'
    weight = 4
